Portability: Variable initialization not at beginning of block
Recent changes in segment.c result in compilation errors on older
compilers like on debian buster or MacOS.

../pspp/src/language/lexer/segment.c:1255:7:
error: a label can only be part of a statement
and a declaration is not a statement
       int eol = at_end_of_line (input, n, eof, 1);

I changed the code such that it compiles on MacOS again to
a more traditional way to avoid the compile error.